dist: xenial
sudo: required

services:
- docker

install:
- docker build -t {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }} .
- docker ps -a

script:
# Adapted from https://stackoverflow.com/a/28123384
- sudo docker run -e CXX -e GH_TOKEN -e TRAVIS_BUILD_NUMBER -e TRAVIS_BRANCH -i {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "set -x && cd /opt/{{ cookiecutter.project_slug }} && git config --global user.email 'travis@travis-ci.org' && git config --global user.name 'Travis CI' && make test && chmod +x /opt/{{ cookiecutter.project_slug }}/ci/after-success.sh && /opt/{{ cookiecutter.project_slug }}/ci/after-success.sh"
