# only build pull requests and merges to master or dev
# adapted from https://stackoverflow.com/a/31882307
if: (type = push AND branch IN (master, dev, cut-cookie)) OR (type = pull_request AND NOT branch =~ /no-ci/)
dist: xenial
sudo: required

services:
- docker

jobs:
  include:
  - stage: Tests

    name: Unit Tests (debug mode)
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script:
    - sudo docker run --cap-add=SYS_ADMIN -e CXX -i {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "set -x && cd /opt/{{ cookiecutter.project_slug }}/tests && make"

  - name: Unit Tests (full debug mode)
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script:
    - sudo docker run --cap-add=SYS_ADMIN -e CXX -i {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "set -x && cd /opt/{{ cookiecutter.project_slug }}/tests && make fulldebug"

  - name: Unit Tests (opt mode)
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script:
    - sudo docker run --cap-add=SYS_ADMIN -e CXX -i {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "set -x && cd /opt/{{ cookiecutter.project_slug }}/tests && make opt"

  - name: Coverage
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script: sudo docker run {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "cd /opt/{{ cookiecutter.project_slug }} && make coverage && bash <(curl -s https://codecov.io/bash)"

  - name: Source
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script: sudo docker run --cap-add=SYS_ADMIN {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "cd /opt/{{ cookiecutter.project_slug }} && make test"

  - name: Docs
    install:
    - docker build -t {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} .
    - docker ps -a
    script: sudo docker run {{ cookiecutter.docker_username }}/{{ cookiecutter.project_slug }} /bin/bash -c "cd /opt/{{ cookiecutter.project_slug }} && make docs"
